title: Comparing Bikeshare and Transit Travel Times with UrbanAccess and Pandana
logo: /assets/img/logo.png
description: Final project for MUSA 550: Geospatial Data Science in Python.
show_downloads: false
repository: Elieri/musa-550-final-project
google_analytics:
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
