title: Estimating Transit Travel Times with UrbanAccess
logo: /assets/img/logo.png
description: Final project for MUSA 550, Geospatial Data Science in Python.
show_downloads: false
google_analytics:
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
